---
title: "Exploratory Analysis"
author: Hailey Quintavalle
format: html
---


```{r message = F}
library(tidyverse)
initial_data <- read_csv("data/mxmh_survey_results.csv")
head(initial_data)
```

### Cleaning up some variable names

```{r}
data <- initial_data |> rename(primary_streaming_service = `Primary streaming service`,
               hours_per_day = `Hours per day`,
               while_working = `While working`,
               fav_genre = `Fav genre`,
               foreign_languages = `Foreign languages`,
               music_effects = `Music effects`,
               Classical = `Frequency [Classical]`,
               Country = `Frequency [Country]`,
               EDM = `Frequency [EDM]`,
               Folk = `Frequency [Folk]`,
               Gospel = `Frequency [Gospel]`,
               Hip_hop = `Frequency [Hip hop]`,
               Jazz = `Frequency [Jazz]`,
               K_pop = `Frequency [K pop]`,
               Latin = `Frequency [Latin]`,
               Lofi = `Frequency [Lofi]`,
               Metal = `Frequency [Metal]`,
               Pop = `Frequency [Pop]`,
               R_B = `Frequency [R&B]`,
               Rap = `Frequency [Rap]`,
               Rock = `Frequency [Rock]`,
               Video_game_music = `Frequency [Video game music]`) |>
  select(-Permissions)
```

### Exploring Mental Health variables

```{r}
ggplot(data = data, aes(x = Anxiety)) +
  geom_histogram()
```

```{r}
ggplot(data = data, aes(x = Insomnia)) +
  geom_histogram()
```


```{r}
ggplot(data = data, aes(x = Depression)) +
  geom_histogram()
```

```{r}
ggplot(data = data, aes(x = OCD)) +
  geom_histogram()
```

*possible question - which musical genres seem to `help` the most for different health disorders?




### Look into demographic around music

```{r}
data |> group_by(primary_streaming_service) |> summarise(round(mean(Age)))
```

```{r}
ggplot(data = data, aes(x = primary_streaming_service, y = Age)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
ggplot(data = data, aes(x = fav_genre, y = Age)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
ggplot(data = data, aes(x = hours_per_day, y = Age)) +
  geom_point()
```

```{r}
ggplot(data = data, aes(x = while_working, y = Age)) +
  geom_boxplot() +
  coord_flip()
```











